databases:
  - name: kaigoshisetsu_db
    databaseName: kaigoshisetsu_db
    user: Kaigoshisetsu
    region: singapore

services:
  - type: web
    name: Kaigoshisetsu
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kaigoshisetsu_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false